Support RMM 26.12 stream API removal (#205)
This nightly CI build https://github.com/sirius-db/sirius/actions/runs/36870079366/job/110395296333 is failing because RMM removed `rmm/cuda_stream_view.hpp` and deprecated stream APIs in RMM 26.12 https://github.com/rapidsai/rmm/pull/2552. cuCascade still includes that header.

```
In file included from /home/runner/actions-runner/_work/sirius/sirius/cucascade/include/cucascade/memory/common.hpp:20,
                 from /home/runner/actions-runner/_work/sirius/sirius/cucascade/src/memory/common.cpp:18:
/home/runner/actions-runner/_work/sirius/sirius/cucascade/include/cucascade/cuda/stream.hpp:13:10: fatal error: rmm/cuda_stream_view.hpp: No such file or directory
   13 | #include <rmm/cuda_stream_view.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

This PR removes that include from cuCascade’s shared stream header, retains it conditionally for older cuDF versions, and updates tests and benchmarks to use supported stream conversions and CUDA stream constants.

cc @bdice

Authors:
  - James Bourbeau (https://github.com/jrbourbeau)

Approvers:
  - Matthijs Brobbel (https://github.com/mbrobbel)

URL: https://github.com/NVIDIA/cuCascade/pull/205